### PR TITLE
Re-use react sdk

### PR DESCRIPTION
**Pull request by yusinto**
I managed to get the react sdk to work with this plugin, and tested this on a gatsby app.

See an example usage of this in the [docs site](https://github.com/launchdarkly/git-gatsby/pull/186).

### CODE REVIEW

**Comment by rmanalan** [comment]
Any luck getting this to work?

**Comment by yusinto** [comment]
> Any luck getting this to work?

Yes it works now, I've updated both PRs. I think it was a caching issue last week, because it just works now that I tried it again.

**Comment by rmanalan** [comment]
Since this is a breaking change, bump the package ver to 0.2 or maybe even 1.0

**Comment by rmanalan** [comment]
Also, update the README to reflect the API change

**Comment by rmanalan** [comment]
Actually, I'll go ahead and merge this and update the README/ver in a separate PR.

**Pull request merged**
